version: '3.4'

services:
  database:
    image: 'postgres'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: igork
      POSTGRES_PASSWORD: qwery3333
      POSTGRES_DB: Login
  server:
    image: server
    ports:
      - 5001:5001
    build: 
       context: .
       dockerfile: ./server.Dockerfile
    depends_on:
      - database
  loginpage:
    image: loginpage
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    depends_on:
      - database
      - server
    ports:
      - 3000:3000
